parameters:
    darvin_image.archive.form_factory.class: Darvin\ImageBundle\Form\Factory\ArchiveFormFactory

    darvin_image.archive.twig_extension.class: Darvin\ImageBundle\Twig\Extension\ArchiveExtension

    darvin_image.archiver.zip.class: Darvin\ImageBundle\Archive\ZipArchiver

services:
    darvin_image.archive.form_factory:
        class: "%darvin_image.archive.form_factory.class%"
        arguments:
            - "@form.factory"
            - "@router"

    darvin_image.archive.twig_extension:
        class:  "%darvin_image.archive.twig_extension.class%"
        public: false
        arguments:
            - "@darvin_image.archive.form_factory"
        tags:
            - { name: twig.extension }

    darvin_image.archiver:
        alias: darvin_image.archiver.zip

    darvin_image.archiver.zip:
        class:  "%darvin_image.archiver.zip.class%"
        public: false
        arguments:
            - "@request_stack"
            - "%darvin_image.archive.cache_dir%"
            - "%darvin_image.archive.filename_suffix%"
            - "%kernel.root_dir%/../web/%darvin_image.upload_path%"
