parameters:
    darvin_image.configuration.pool.class: Darvin\ImageBundle\Configuration\ConfigurationPool

services:
    darvin_image.configuration.pool:
        class: %darvin_image.configuration.pool.class%
        arguments:
            - "@darvin_config.security.configuration_authorization_checker"
