parameters:
    darvin_image.form.type.image.class: Darvin\ImageBundle\Form\Type\ImageType

services:
    darvin_image.form.type.image:
        class: %darvin_image.form.type.image.class%
        tags:
            - { name: form.type, alias: darvin_image }
