parameters:
    darvin_image.image.copy_cloned_file_event_subscriber.class: Darvin\ImageBundle\EventListener\CopyClonedImageFileSubscriber

    darvin_image.image.form_type.class: Darvin\ImageBundle\Form\Type\Image\ImageType

    darvin_image.image.rename_event_subscriber.class: Darvin\ImageBundle\EventListener\RenameImageSubscriber

    darvin_image.image.update_properties_event_subscriber.class: Darvin\ImageBundle\EventListener\UpdateImagePropertiesSubscriber

services:
    _defaults:
        public: true

    darvin_image.image.copy_cloned_file_event_subscriber:
        class: "%darvin_image.image.copy_cloned_file_event_subscriber.class%"
        arguments:
            - "@filesystem"
            - "@vich_uploader.storage"
            - "%kernel.cache_dir%"
        tags:
            - { name: kernel.event_subscriber }

    darvin_image.image.form_type:
        class: "%darvin_image.image.form_type.class%"
        arguments:
            - "@darvin_image.size.describer"
        tags:
            - { name: form.type }

    darvin_image.image.rename_event_subscriber:
        class:  "%darvin_image.image.rename_event_subscriber.class%"
        public: false
        arguments:
            - "@filesystem"
            - "@vich_uploader.storage"
            - "%kernel.cache_dir%"
        tags:
            - { name: doctrine.event_subscriber }

    darvin_image.image.update_properties_event_subscriber:
        class: "%darvin_image.image.update_properties_event_subscriber.class%"
        tags:
            - { name: kernel.event_subscriber }
