parameters:
    darvin_image.imagine.cache_resolver.class: Darvin\ImageBundle\Imagine\Cache\Resolver\Resolver

services:
    darvin_image.imagine.cache_resolver:
        class:  "%darvin_image.imagine.cache_resolver.class%"
        public: false
        arguments:
            - "@filesystem"
            - "@router.request_context"
            - "%darvin_image.imagine.cache_resolver.web_root%"
            - "%darvin_image.imagine.cache_resolver.cache_prefix%"
        tags:
            - { name: liip_imagine.cache.resolver, resolver: darvin_image }
