services:
    darvin_image.namer.file:
        alias:      darvin_file.namer.file
        public:     true
        deprecated: 'File namer "%alias_id%" is deprecated. Use "darvin_file.namer.file" instead.'
