parameters:
    darvin_image.archive.twig_extension.class: Darvin\ImageBundle\Twig\Extension\ArchiveExtension

services:
    darvin_image.archive.twig_extension:
        class:  "%darvin_image.archive.twig_extension.class%"
        public: false
        arguments:
            - "@?darvin_image.archive.form_factory"
        tags:
            - { name: twig.extension }
