darvin_image:
    action:
        edit:
            fields:
                Darvin\ImageBundle\Entity\Image\AbstractImage:
                    name: ~
                    translations:
                        type: A2lix\TranslationFormBundle\Form\Type\TranslationsType
                        options:
                            label: false
