darvin_image:
    action:
        edit:
            fields:
                Darvin\ImageBundle\Entity\Image\AbstractImage:
                    name:
                        options:
                            help:               image.help.name
                            translation_domain: darvin_image
                    translations:
                        type: A2lix\TranslationFormBundle\Form\Type\TranslationsType
                        options:
                            label: false
