vich_uploader:
    db_driver: orm
    mappings:
        darvin_image:
            uri_prefix:         '/%image_path%'
            upload_destination: '%kernel.project_dir%/public/%image_path%'
            directory_namer:    darvin_image.namer.directory
            namer:              darvin_image.namer.file
