parameters:
    darvin_image.image.list_orphans_command.class:      Darvin\ImageBundle\Command\ListOrphanImagesCommand
    darvin_image.image.list_orphans_command.name:       darvin:image:orphans
    darvin_image.image.list_orphans_command.chunk_size: 50

services:
    darvin_image.image.list_orphans_command:
        class: '%darvin_image.image.list_orphans_command.class%'
        arguments:
            - '%darvin_image.image.list_orphans_command.name%'
            - '@doctrine.orm.entity_manager'
            - '@filesystem'
            - '@vich_uploader.metadata_reader'
            - '@vich_uploader.storage'
            - '%darvin_image.image.list_orphans_command.chunk_size%'
            - '%vich_uploader.mappings%'
        tags:
            - { name: console.command }
